Creating a 2D tensor

In [5]:
import numpy as np 
import matplotlib.pyplot as plt
import torch
import pandas as pd

In [9]:
# torch tensor is a rectangular matrix with each nested list corresponding to a different row of the torch tensor
a=[[11,12,13],[21,22,23],[31,32,33]]
A=torch.tensor(a)
print('Data type', A.dtype)
print('Data type', type(A))
print(A)

Data type torch.int64
Data type <class 'torch.Tensor'>
tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])


In [12]:
# get number of dimensions of torch tensor
print(A.ndimension())

# return number of rows and columns
print(A.shape)

# return number of elements in the torch tensor
print(A.numel())

2
torch.Size([3, 3])
9


Indexing and slicing

In [24]:
print(A[0][0])
print(A[0][0].item())

tensor(11)
11


In [25]:
print(A[1][2])
print(A[1][2].item())

tensor(23)
23


In [28]:
print(A[0][:2])

tensor([11, 12])


In [21]:
print(A[1:3,2])

tensor([23, 33])


Basic operations

In [30]:
#matrix addition
X=torch.tensor([[1,0],[0,1]])
Y=torch.tensor([[2,1],[1,2]])
Z = X+Y
print(Z)

tensor([[3, 1],
        [1, 3]])


In [31]:
# matrix multiplication with a scalar
Y=torch.tensor([[2,1],[1,2]])
Z=2*Y
print(Z)

tensor([[4, 2],
        [2, 4]])


In [32]:
#element-wise multiplication (Hadamard product)
X=torch.tensor([[1,0],[0,1]])
Y=torch.tensor([[2,1],[1,2]])
Z = X*Y
print(Z)

tensor([[2, 0],
        [0, 2]])


In [35]:
#matrix multiplication
# number of columns must be equal to the number of rows
A=torch.tensor([[0,1,1],[1,0,1]])
B=torch.tensor([[1,1],[1,1],[-1,1]])
C=torch.mm(A,B)
print(C)

tensor([[0, 2],
        [0, 2]])


### Quiz

In [36]:
a=torch.tensor([[0,1,1],[1,0,1]])
print(a.size(),a.ndimension())

torch.Size([2, 3]) 2


In [38]:
df = pd.DataFrame({'A':[11, 33, 22],'B':[3, 3, 2]})
# convert the pandas dataframe to a tensor
torch.Tensor(df.values)

tensor([[11.,  3.],
        [33.,  3.],
        [22.,  2.]])

In [42]:
X = torch.tensor([[1, 0], [0, 1]])
Y = torch.tensor([[2, 1], [1, 2]]) 
X_times_Y = X * Y
print(X_times_Y)

tensor([[2, 0],
        [0, 2]])


In [43]:
A = torch.tensor([[0, 1, 1], [1, 0, 1]])
B = torch.tensor([[1, 1], [1, 1], [-1, 1]])
A_times_B = torch.mm(A,B)
print(A_times_B)

tensor([[0, 2],
        [0, 2]])
